server:
  port: 8081
spring:
  jackson:
    time-zone: America/Lima
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: chris
    password: chris
  sql:
    init:
      continue-on-error: true
      mode: always
      schema-locations: classpath:import.sql